nginx:
  image: nginx:latest
  restart: always
  ports:
    - 80:80
    - 443:443
  log_driver: syslog
  links:
    - wordpress
  volumes:
    - ./wp:/var/www/html:ro
    - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./var/log/nginx:/var/log/nginx

mysql:
   image: mariadb:latest
   restart: always
   volumes:
    - ./var/mysql:/var/lib/mysql
   environment:
    MYSQL_ROOT_PASSWORD: password

wordpress:
  image: evild/docker-wordpress-fpm:latest
  restart: always
  links:
    - mysql
  volumes:
    - ./wp:/var/www/html
  environment:
    WORDPRESS_DB_NAME: wpdb
    WORDPRESS_TABLE_PREFIX: wp_
